# Generated by Django 5.2 on 2025-05-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
