# Generated by Django 5.2 on 2025-05-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0003_alter_application_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
