# Generated by Django 5.2 on 2025-05-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0005_alter_application_cover_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date',
        ),
        migrations.AddField(
            model_name='application',
            name='date_applied',
            field=models.DateField(null=True),
        ),
    ]
