# Generated by Django 5.2 on 2025-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0006_remove_application_date_application_date_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='called_back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='date_callback',
            field=models.DateField(null=True),
        ),
    ]
