# Generated by Django 5.2 on 2025-05-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0007_application_called_back_application_date_callback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_callback',
            field=models.DateField(blank=True, null=True),
        ),
    ]
