# Generated by Django 5.2 on 2025-05-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0009_application_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='date_callback',
        ),
        migrations.AddField(
            model_name='application',
            name='callback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='findjob.callback'),
        ),
    ]
