# Generated by Django 5.2 on 2025-05-06 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0010_callback_remove_application_date_callback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='callback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='findjob.callback'),
        ),
    ]
