# Generated by Django 5.2 on 2025-05-06 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0011_alter_application_callback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='callback',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='findjob.callback'),
        ),
    ]
