# Generated by Django 5.2 on 2025-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0012_alter_application_callback'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
