# Generated by Django 5.2 on 2025-05-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0013_application_declined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='declined',
        ),
        migrations.AddField(
            model_name='application',
            name='state',
            field=models.CharField(choices=[('OP', 'Open'), ('NO', 'Declined'), ('OK', 'Accepted')], default='OP', max_length=2),
        ),
    ]
