# Generated by Django 5.2 on 2025-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0014_remove_application_declined_application_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
