# Generated by Django 5.2 on 2025-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findjob', '0015_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
